version: '2.4'
services:
   calc_nuxt:
      container_name: calc_nuxt
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - '8083:3000'
      volumes:
         - ./:/app
      tty: true
